-- ----------------------------------------------------------------------
-- SQL data bulk transfer script generated by the MySQL Migration Toolkit
-- ----------------------------------------------------------------------

-- Disable foreign key checks
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

INSERT INTO `digicheck_dbo`.`ESTADO`(`EST_NOMBRE`, `EST_CODIGO`)
VALUES ('Aguascalientes', '1'),
  ('Durango', '10'),
  ('Estado de M�xico', '11'),
  ('Guanajuato', '12'),
  ('Guerrero', '13'),
  ('Guerrero', '14'),
  ('Jalisco', '15'),
  ('Michoac�', '16'),
  ('Morelos', '17'),
  ('Nayarit', '18'),
  ('Nuevo Le�', '19'),
  ('Baja California', '2'),
  ('Oaxaca', '20'),
  ('Puebla', '21'),
  ('Quer�taro', '22'),
  ('Quintana Roo', '23'),
  ('San Luis Potos�', '24'),
  ('Sinaloa', '25'),
  ('Sonora', '26'),
  (' Tabasco', '27'),
  ('Tamaulipas', '28'),
  ('Tlaxcala', '29'),
  ('Baja California Sur', '3'),
  ('Veracruz', '30'),
  ('Yucat�', '31'),
  ('Zacatecas', '32'),
  ('Campeche', '4'),
  ('Chiapas', '5'),
  ('Chihuahua', '6'),
  ('Coahuila', '7'),
  ('Colima', '8'),
  ('Distrito Federal', '9');

INSERT INTO `digicheck_dbo`.`PERMISO`(`PER_ID`, `PER_DESCRIPCION`, `PET_CODE`)
VALUES (1, 'Configurar Scanner', '000');

INSERT INTO `digicheck_dbo`.`SUCURSAL`(`SUC_ID`, `SUC_NOMBRE`, `SUC_DIRECCION`, `SUC_COLONIA`, `SUC_CODIGO_POSTAL`, `SUC_CIUDAD`, `EST_CODIGO`)
VALUES (1, '4444', 'Guadalajara', 'centro', '12345', 'Guadalajara', '14'),
  (2, 'Empresa 1', 'Direccion 1', 'Autlan', '33333', 'Zaragoza # 20', '10'),
  (3, 'Clodosoft', 'Tepic # 134', 'Plaza Guadalupe', NULL, 'Zapopan, Jalisco', '1'),
  (5, 'Jose', '', 'Autlan 7', '45465', 'Puto', '13'),
  (6, '3123', 'sdfdsfsd', 'Municipio 6', '34343', 'Domicilio 6', '31'),
  (8, 'sfsdfdsfsdf', 'Guadalajara', 'centro', NULL, 'Guadalajara', '14'),
  (11, 'Test 11', '', 'Municipio 11', '3232', 'Test 11', '25'),
  (12, 'KKKKKKK', '', 'DSFSD', '2323', 'SDFSD', '19'),
  (17, 'Banamex', '', 'Tlaquepaque', NULL, 'Centro', '11'),
  (18, 'Manchester', '', 'Tlaquepaque', NULL, 'Celeste', '15'),
  (19, 'Test 5', '', 'Autlan', NULL, 'privada arquitos', '1'),
  (20, 'Test 5', '', 'Autlan', NULL, 'privada arquitos', '1'),
  (21, 'Test 6', '', 'Autlan 6', NULL, 'privada arquitos 6', '1'),
  (22, 'Test 9', '', 'Autlan 9', '7777', 'privada arquitos 9', '18');

INSERT INTO `digicheck_dbo`.`TIPO_PERMISO`(`PET_CODE`, `PET_DESCRIPCION`)
VALUES ('000', 'Scanner'),
  ('001', 'Digitalizar');

INSERT INTO `digicheck_dbo`.`USUARIO`(`USU_LOGIN`, `USU_NOMBRE`, `USU_PASSWORD`, `SUC_ID`)
VALUES ('carlos', 'Carlos', '', 1),
  ('edgar', 'Edgar Joao', 'edgar', 1),
  ('jose', 'Jose Delgado', 'jose', 1);

INSERT INTO `digicheck_dbo`.`USUARIO_PERMISO`(`USU_LOGIN`, `PER_ID`, `USP_FECHA`)
VALUES ('edgar', 1, '2011-07-24 17:29:30');

INSERT INTO `digicheck_dbo`.`BANCO`(`BAN_ID`, `ABA`, `DESCRIPCION`)
VALUES (3, 'Banamexx', '1223243324'),
  (7, 'Bansi 1', '21232323'),
  (26, 'Santander', 'Account 134'),
  (27, 'Santander', 'Account 134'),
  (36, 'fsdf - Test 1', 'Cuenta Test 1'),
  (40, 'Banco Google', 'Ninguna'),
  (53, 'Test 44', 'Test 44'),
  (54, 'Test5', 'Test 5'),
  (66, 'Cuarenta y Cinco', 'Cuarenta'),
  (67, 'IXE 35', '33333335'),
  (68, 'IXE 31', '3333331'),
  (69, 'IXE 311', '33333311'),
  (70, 'IXE 77', '21132343'),
  (71, 'Santander', 'Account 135'),
  (73, 'Test 999', '99999999999'),
  (76, 'HSBC', '7474847'),
  (77, '2324555', 'Test 11');

INSERT INTO `digicheck_dbo`.`DIVISA`(`DIV_ID`, `DIV_IMAGEN`, `DIV_NOMBRE`, `DIV_CODIGO`)
VALUES (10, NULL, 'Pesos', '232'),
  (12, NULL, 'EUROS', '243'),
  (14, 0x, 'INDIA 4', '768'),
  (18, 0x, '23123dsfsf', '312'),
  (23, 0x, 'EURO', '123'),
  (28, 0x, 'Requerido', '132'),
  (30, 0x, 'Test 22', '222'),
  (41, 0x, 'Seis', '666');

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

-- End of script
