USE [digicheck]
GO
/****** Object:  Table [dbo].[DOCUMENTO]    Script Date: 08/22/2011 00:39:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DOCUMENTO](
	[DOC_ID] [int] IDENTITY(1,1) NOT NULL,
	[DOC_NUMERO] [int] NOT NULL,
	[DOC_ARCHIVO] [varbinary](1) NOT NULL,
	[DOT_ID] [char](1) NULL,
	[CHQ_ID] [int] NULL,
 CONSTRAINT [IDX_PK_DOC] PRIMARY KEY CLUSTERED 
(
	[DOC_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_CHQ_ID_DOC] FOREIGN KEY([CHQ_ID])
REFERENCES [dbo].[CHEQUE] ([CHQ_ID])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [FK_CHQ_ID_DOC]
GO
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DOT_DOC] FOREIGN KEY([DOT_ID])
REFERENCES [dbo].[TIPO_DOCUMENTO] ([DOT_ID])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [FK_DOT_DOC]