Como insertar imagenes
Modificar la columna DOC_ARCHIVO de un tamanio MAX

INSERT INTO DOCUMENTO (DOC_NUMERO,DOT_ID, CHQ_ID, DOC_ARCHIVO)
SELECT 12,'C',1,BulkColumn FROM OPENROWSET(Bulk 'C:\Cheque01.jpg', SINGLE_BLOB) AS BLOB




Sesiones abiertas
SELECT SPID,STATUS,PROGRAM_NAME,LOGINAME=RTRIM(LOGINAME),HOSTNAME,CMD
FROM  MASTER.DBO.SYSPROCESSES
WHERE DB_NAME(DBID) = 'digicheck' AND DBID != 0 