USE [digicheck]
GO
/****** Object:  Table [dbo].[LOTE]    Script Date: 08/22/2011 00:40:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOTE](
	[LOT_REFERENCIA] [varchar](100) NOT NULL,
	[LOT_IMPORTE] [decimal](18, 2) NOT NULL,
	[USU_LOGIN] [varchar](20) NOT NULL,
	[SUC_ID] [int] NOT NULL,
	[DIV_ID] [int] NOT NULL,
	[LOT_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOT_DOCUMENTOS] [int] NOT NULL,
	[LOT_FECHA] [datetime] NOT NULL,
	[LOT_FECHA_ALTA] [datetime] NOT NULL,
 CONSTRAINT [IDX_PK_LOT] PRIMARY KEY CLUSTERED 
(
	[LOT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_DIV_LOT] FOREIGN KEY([DIV_ID])
REFERENCES [dbo].[DIVISA] ([DIV_ID])
GO
ALTER TABLE [dbo].[LOTE] CHECK CONSTRAINT [FK_DIV_LOT]
GO
ALTER TABLE [dbo].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_SUC_LOT] FOREIGN KEY([SUC_ID])
REFERENCES [dbo].[SUCURSAL] ([SUC_ID])
GO
ALTER TABLE [dbo].[LOTE] CHECK CONSTRAINT [FK_SUC_LOT]
GO
ALTER TABLE [dbo].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_USU_LOT] FOREIGN KEY([USU_LOGIN])
REFERENCES [dbo].[USUARIO] ([USU_LOGIN])
GO
ALTER TABLE [dbo].[LOTE] CHECK CONSTRAINT [FK_USU_LOT]