insert into estado (est_codigo,est_nombre) values ('1','Aguascalientes')
insert into estado (est_codigo,est_nombre) values ('2','Baja California')
insert into estado (est_codigo,est_nombre) values ('3','Baja California Sur')
insert into estado (est_codigo,est_nombre) values ('4','Campeche')
insert into estado (est_codigo,est_nombre) values ('5','Chiapas')
insert into estado (est_codigo,est_nombre) values ('6','Chihuahua')
insert into estado (est_codigo,est_nombre) values ('7','Coahuila')
insert into estado (est_codigo,est_nombre) values ('8','Colima')
insert into estado (est_codigo,est_nombre) values ('9','Distrito Federal')
insert into estado (est_codigo,est_nombre) values ('10','Durango')
insert into estado (est_codigo,est_nombre) values ('11','Estado de México')
insert into estado (est_codigo,est_nombre) values ('12','Guanajuato')
insert into estado (est_codigo,est_nombre) values ('13','Guerrero')
insert into estado (est_codigo,est_nombre) values ('14','Hidalgo')
insert into estado (est_codigo,est_nombre) values ('15','Jalisco')
insert into estado (est_codigo,est_nombre) values ('16','Michoacán')
insert into estado (est_codigo,est_nombre) values ('17','Morelos')
insert into estado (est_codigo,est_nombre) values ('18','Nayarit')
insert into estado (est_codigo,est_nombre) values ('19','Nuevo León')
insert into estado (est_codigo,est_nombre) values ('20','Oaxaca')
insert into estado (est_codigo,est_nombre) values ('21','Puebla')
insert into estado (est_codigo,est_nombre) values ('22','Querétaro')
insert into estado (est_codigo,est_nombre) values ('23','Quintana Roo')
insert into estado (est_codigo,est_nombre) values ('24','San Luis Potosí')
insert into estado (est_codigo,est_nombre) values ('25','Sinaloa')
insert into estado (est_codigo,est_nombre) values ('26','Sonora')
insert into estado (est_codigo,est_nombre) values ('27',' Tabasco')
insert into estado (est_codigo,est_nombre) values ('28','Tamaulipas')
insert into estado (est_codigo,est_nombre) values ('29','Tlaxcala')
insert into estado (est_codigo,est_nombre) values ('30','Veracruz')
insert into estado (est_codigo,est_nombre) values ('31','Yucatán')
insert into estado (est_codigo,est_nombre) values ('32','Zacatecas')