USE [digicheck]
GO
/****** Object:  Table [dbo].[CHEQUE]    Script Date: 08/22/2011 00:38:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHEQUE](
	[CHQ_ID] [int] NOT NULL,
	[LOT_ID] [int] NOT NULL,
	[CHQ_ABBA] [varchar](50) NOT NULL,
	[CHQ_CUENTA] [varchar](20) NOT NULL,
	[CHQ_IMPORTE] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_CHEQUE] PRIMARY KEY CLUSTERED 
(
	[CHQ_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[CHEQUE]  WITH CHECK ADD  CONSTRAINT [FK_LOT_ID_CHQ] FOREIGN KEY([LOT_ID])
REFERENCES [dbo].[LOTE] ([LOT_ID])
GO
ALTER TABLE [dbo].[CHEQUE] CHECK CONSTRAINT [FK_LOT_ID_CHQ]